"""added image fields

Revision ID: 8afe4f9feb3e
Revises: e198b21a076c
Create Date: 2025-11-18 13:01:34.889281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8afe4f9feb3e'
down_revision: Union[str, Sequence[str], None] = 'e198b21a076c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('alt_text', sa.String(), nullable=True))
    op.add_column('product_images', sa.Column('is_primary', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'is_primary')
    op.drop_column('product_images', 'alt_text')
    # ### end Alembic commands ###
