"""added shipping address fields

Revision ID: 9eb44616581a
Revises: 336cf343dc3f
Create Date: 2025-11-18 18:34:44.948945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb44616581a'
down_revision: Union[str, Sequence[str], None] = '336cf343dc3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('street', sa.String(), nullable=True))
    op.add_column('addresses', sa.Column('landmark', sa.String(), nullable=True))
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.drop_column('addresses', 'address_line')
    op.add_column('orders', sa.Column('shipping_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_phone', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_address', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_city', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_state', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_pincode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipping_pincode')
    op.drop_column('orders', 'shipping_state')
    op.drop_column('orders', 'shipping_city')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'shipping_phone')
    op.drop_column('orders', 'shipping_name')
    op.add_column('addresses', sa.Column('address_line', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_column('addresses', 'landmark')
    op.drop_column('addresses', 'street')
    # ### end Alembic commands ###
